config/routes.rb
MystroVolley::Engine.routes.draw do
  match "browser" => "home#browser"

  resources :projects
  resources :branches
  resources :versions do
    get "deploy", on: :member
    post "queue", on: :member
  end

  constraints(project: /[\w\d\.]+/,branch: /[\w\d\.]+/,version: /[\w\d\.]+/) do
    match "/:project", to: "home#show"
    match "/:project/:branch", to: "home#show"
    match "/:project/:branch/:version", to: "home#show"
  end

  #match "/__better_errors/:id/:thing" => main_app.root + "/__better_errors/%{id}/%{thing}"

  root to: "home#index"
end

MystroServer::Application.routes.draw do
  mount MystroVolley::Engine => "/plugins/volley"
end

app/models/jobs/volley/destroy/version.rb
class Jobs::Volley::Destroy::Version < Jobs::Volley::Base
  def work
    info "volley: #{Volley::Version::STRING}"
    info "destroy version #{model.to_s}"
    p = model.project
    b = model.branch
    v = model
    info "project: #{p.name}"
    info "branch:  #{b.name}"
    info "version: #{v.name}"
    raise "something wrong with version heirarchy" unless p && b && v
    publisher.delete_version(p.name, b.name, v.name)
  ensure
    model.destroy
  end
end

app/models/mystro_volley/branch.rb
module MystroVolley
  class Branch
    include Mongoid::Document
    include Mongoid::Timestamps

    field :name, type: String

    has_many :versions, class_name: 'MystroVolley::Version'
    belongs_to :project, class_name: 'MystroVolley::Project'

    def to_s
      "#{project.to_s}@#{name}"
    end
  end
end

app/models/mystro_volley/install.rb
module MystroVolley
  class Install
    include Mongoid::Document
    include Mongoid::Timestamps

    belongs_to :compute, class_name: "Compute"
    belongs_to :version, class_name: "MystroVolley::Version"
  end
end

app/models/mystro_volley/project.rb
module MystroVolley
  class Project
    include Mongoid::Document
    include Mongoid::Timestamps

    has_many :branches, class_name: 'MystroVolley::Branch'

    field :name, type: String

    def to_s
      name
    end
  end
end

app/models/mystro_volley/version.rb
module MystroVolley
  class Version
    include Mongoid::Document
    include Mongoid::Timestamps

    belongs_to :branch, class_name: 'MystroVolley::Branch'

    field :name, type: String
    field :files, type: Array
    field :timestamp, type: DateTime
    field :latest, type: Boolean

    def project
      branch ? branch.project : nil
    end

    def to_s
      "#{branch.to_s}:#{name}" #" timestamp:#{timestamp} files:#{files ? files.count : 0}"
    end

    class << self
      def find_by_name(name)
        (p, b, v) = name.split(/[\@\:]/)
        #puts "find_by_name: #{p} #{b} #{v}"
        project = MystroVolley::Project.where(name: p).first
        if project
          branch = project.branches.where(name: b).first
          if branch
            version = branch.versions.where(name: v).first
            return version if version
          end
        end
        nil
      end
    end
  end
end

app/controllers/mystro_volley/application_controller.rb
class MystroVolley::ApplicationController < ApplicationController
  include MystroVolley::ApplicationHelper
end

app/controllers/mystro_volley/branches_controller.rb
require_dependency "mystro_volley/application_controller"

module MystroVolley
  class BranchesController < ApplicationController
    # GET /branches
    # GET /branches.json
    def index
      @branches = Branch.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @branches }
      end
    end
  
    # GET /branches/1
    # GET /branches/1.json
    def show
      @branch = Branch.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @branch.versions }
      end
    end

    ## GET /branches/new
    ## GET /branches/new.json
    #def new
    #  @branch = Branch.new
    #
    #  respond_to do |format|
    #    format.html # new.html.erb
    #    format.json { render json: @branch }
    #  end
    #end
    #
    ## GET /branches/1/edit
    #def edit
    #  @branch = Branch.find(params[:id])
    #end
    #
    ## POST /branches
    ## POST /branches.json
    #def create
    #  @branch = Branch.new(params[:branch])
    #
    #  respond_to do |format|
    #    if @branch.save
    #      format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
    #      format.json { render json: @branch, status: :created, location: @branch }
    #    else
    #      format.html { render action: "new" }
    #      format.json { render json: @branch.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
    #
    ## PUT /branches/1
    ## PUT /branches/1.json
    #def update
    #  @branch = Branch.find(params[:id])
    #
    #  respond_to do |format|
    #    if @branch.update_attributes(params[:branch])
    #      format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
    #      format.json { head :no_content }
    #    else
    #      format.html { render action: "edit" }
    #      format.json { render json: @branch.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
  
    # DELETE /branches/1
    # DELETE /branches/1.json
    def destroy
      @branch = Branch.find(params[:id])
      Jobs::Volley::Destroy::Branch.create(data: {id: @branch.id, class: "MystroVolley::Branch"}).enqueue
  
      respond_to do |format|
        format.html { redirect_to branches_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/mystro_volley/home_controller.rb
require_dependency "mystro_volley/application_controller"
class MystroVolley::HomeController < ApplicationController
  include MystroVolley::ApplicationHelper

  def index
    #@projects = MystroVolley::Project.all
    @myversions = MystroVolley::Version.desc(:timestamp).where(latest: true)
  end

  def browser
    @projects = MystroVolley::Project.all
  end

  def show
    p = params[:project]
    b = params[:branch]
    v = params[:version]

    if p
      @project = MystroVolley::Project.where(name: p).first

      if @project
        if b
          @branch = @project.branches.where(name: b).first
          if @branch
            if v
              @version = @branch.versions.where(name: v).first
              if @version
                return render "mystro_volley/versions/show"
              else
                flash.now[:error] = "version #{v} not found"
                return render "mystro_volley/branches/show"
              end
            else
              return render "mystro_volley/branches/show"
            end
          else
            flash.now[:error] = "branch #{b} not found"
            return render "mystro_volley/projects/show"
          end
        else
          return render "mystro_volley/projects/show"
        end
      else
        #@myversions = MystroVolley::Version.desc(:timestamp).where(latest: true)
        #render "mystro_volley/versions/index"
        flash.now[:error] = "project #{p} not found"
      end
    else
      @myversions = MystroVolley::Version.desc(:timestamp).where(latest: true)
      render "mystro_volley/versions/index"
    end
  end
end

app/controllers/mystro_volley/projects_controller.rb
require_dependency "mystro_volley/application_controller"

module MystroVolley
  class ProjectsController < ApplicationController
    # GET /projects
    # GET /projects.json
    def index
      @projects = Project.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @projects }
      end
    end
  
    # GET /projects/1
    # GET /projects/1.json
    def show
      @project = Project.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @project.branches }
      end
    end
  
    # GET /projects/new
    ## GET /projects/new.json
    #def new
    #  @project = Project.new
    #
    #  respond_to do |format|
    #    format.html # new.html.erb
    #    format.json { render json: @project }
    #  end
    #end
    #
    ## GET /projects/1/edit
    #def edit
    #  @project = Project.find(params[:id])
    #end
    #
    ## POST /projects
    ## POST /projects.json
    #def create
    #  @project = Project.new(params[:project])
    #
    #  respond_to do |format|
    #    if @project.save
    #      format.html { redirect_to @project, notice: 'Project was successfully created.' }
    #      format.json { render json: @project, status: :created, location: @project }
    #    else
    #      format.html { render action: "new" }
    #      format.json { render json: @project.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
    #
    ## PUT /projects/1
    ## PUT /projects/1.json
    #def update
    #  @project = Project.find(params[:id])
    #
    #  respond_to do |format|
    #    if @project.update_attributes(params[:project])
    #      format.html { redirect_to @project, notice: 'Project was successfully updated.' }
    #      format.json { head :no_content }
    #    else
    #      format.html { render action: "edit" }
    #      format.json { render json: @project.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
  
    # DELETE /projects/1
    # DELETE /projects/1.json
    def destroy
      @project = Project.find(params[:id])
      Jobs::Volley::Destroy::Project.create(data: {id: @project.id, class: "MystroVolley::Project"}).enqueue
  
      respond_to do |format|
        format.html { redirect_to projects_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/mystro_volley/versions_controller.rb
require_dependency "mystro_volley/application_controller"

module MystroVolley
  class VersionsController < ApplicationController
    # GET /versions
    # GET /versions.json
    def index
      @versions = Version.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @versions }
      end
    end
  
    # GET /versions/1
    # GET /versions/1.json
    def show
      @version = Version.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @version.files.map {|e| {name: e, _id:"blarg"}} }
      end
    end

    # GET /versions/1/deploy
    def deploy
      @version = Version.find(params[:id])
      render "deploy", layout: false
    end

    # POST /versions/1/queue
    def queue
      @version = Version.find(params[:id])
      @environment = Environment.find(params[:environment])
      @role = Role.find(params[:role])
      j = Jobs::Volley::Deploy.create(data: {version: @version.to_s, environment: @environment.name, organization: current_user.organization, force: params[:force] == 1, role: @role.name})
      j.enqueue
      render status: :ok, json: {errors: false}
    rescue => e
      render status: :bad_request, json: {errors: true, message: e.message}
    end
  
    ## GET /versions/new
    ## GET /versions/new.json
    #def new
    #  @version = Version.new
    #
    #  respond_to do |format|
    #    format.html # new.html.erb
    #    format.json { render json: @version }
    #  end
    #end
    #
    ## GET /versions/1/edit
    #def edit
    #  @version = Version.find(params[:id])
    #end
    #
    ## POST /versions
    ## POST /versions.json
    #def create
    #  @version = Version.new(params[:version])
    #
    #  respond_to do |format|
    #    if @version.save
    #      format.html { redirect_to @version, notice: 'Version was successfully created.' }
    #      format.json { render json: @version, status: :created, location: @version }
    #    else
    #      format.html { render action: "new" }
    #      format.json { render json: @version.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
    #
    ## PUT /versions/1
    ## PUT /versions/1.json
    #def update
    #  @version = Version.find(params[:id])
    #
    #  respond_to do |format|
    #    if @version.update_attributes(params[:version])
    #      format.html { redirect_to @version, notice: 'Version was successfully updated.' }
    #      format.json { head :no_content }
    #    else
    #      format.html { render action: "edit" }
    #      format.json { render json: @version.errors, status: :unprocessable_entity }
    #    end
    #  end
    #end
  
    # DELETE /versions/1
    # DELETE /versions/1.json
    def destroy
      @version = Version.find(params[:id])
      Jobs::Volley::Destroy::Version.create(data: {id: @version.id, class: "MystroVolley::Version"}).enqueue

      respond_to do |format|
        format.html { redirect_to versions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/mystro_volley/application_helper.rb
module MystroVolley
  module ApplicationHelper
    def path_helper(o)
      case o.class
        when MystroVolley::Project then root_path + "#{o.name}"
        when MystroVolley::Branch then root_path + "#{o.project.name}/#{o.name}"
        when MystroVolley::Version then root_path + "#{o.project.name}/#{o.branch.name}/#{o.name}"
        else root_path
      end
    rescue => e
      flash.now[:error] = "could not find path for #{o}"
      root_path
    end
  end
end

app/helpers/mystro_volley/branches_helper.rb
module MystroVolley
  module BranchesHelper
  end
end

app/helpers/mystro_volley/projects_helper.rb
module MystroVolley
  module ProjectsHelper
  end
end

app/helpers/mystro_volley/versions_helper.rb
module MystroVolley
  module VersionsHelper
  end
end

app/views/mystro_volley/versions/_form.html.erb
<%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :latest %><br />
    <%= f.check_box :latest %>
  </div>
  <div class="field">
    <%= f.label :files %><br />
    <%= f.text_field :files %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mystro_volley/versions/_list.html.erb
<h4>Versions</h4>
<table class="table table-condensed table-striped tablesorter">
  <thead>
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th>Files</th>
    <th>Latest</th>
    <% if defined?(showlinks) && showlinks == true %>
    <th></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <%= render versions, showlinks: true %>
  </tbody>
</table>

app/views/mystro_volley/versions/_version.html.erb
<tr>
  <td><%= link_to version.to_s, mystro_volley.version_path(version) %></td>
  <td><%= distance_of_time_in_words_to_now(version.timestamp) %></td>
  <td><%= version.files.count %></td>
  <td><%= version.latest %></td>
  <% if defined?(showlinks) && showlinks == true %>
  <td class="links">
    <%= link_to "#", class: "btn btn-mini volley-deploy", data: {url: "/plugins/volley/versions/#{version.id}/deploy"} do %>
        <i class="icon-share"></i>
    <% end %>                                                                                                                          <!-- , method: :delete, confirm: "Are you sure you wish to remove #{version.to_s}?" -->
    <%= link_to "#", class: "btn btn-mini btn-danger delete_me", confirm: "Are you sure you want to delete #{version.to_s}?", data: {id: version.id.to_s, type: "versions", base: "/plugins/volley"} do %>
        <i class="icon-remove-sign"></i>
    <% end %>
  </td>
  <% end %>
</tr>

app/views/mystro_volley/versions/deploy.html.erb
<div id="deploy_dialog_contents">
<%= form_tag "/plugins/volley/versions/#{@version.id}/queue", id: "deploy_form", class: "form-horizontal" do %>
    <div class="form-inputs">
      <div class="control-group">
        <label>&nbsp;</label>
        <div class="controls">
          Deploying <strong><%= @version %></strong>
        </div>
      </div>
      <div class="control-group select required">
        <label class="select required control-label" for="environment_template"><abbr title="required">*</abbr> Environment</label>
        <div class="controls">
          <%= select_tag(:environment, options_from_collection_for_select(Environment.for_organization(current_user.organization), 'id', 'name')) %>
        </div>
      </div>
      <div class="control-group select required">
        <label class="select required control-label" for="environment_template"><abbr title="required">*</abbr> Role</label>
        <div class="controls">
          <%= select_tag(:role, options_from_collection_for_select(Role.deployable.all, 'id', 'name')) %>
        </div>
      </div>
      <div class="control-group boolean optional">
        <label class="boolean optional control-label" for="environment_protected">Force</label>
        <div class="controls">
          <!--<input name= type="hidden" value="0"><label class="checkbox"><input class="boolean optional" id="environment_protected" name="environment[protected]" type="checkbox" value="1"></label>-->
          <%= check_box_tag(:force) %>
        </div>
      </div>
    </div>
<% end %>
</div>

app/views/mystro_volley/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/mystro_volley/versions/index.html.erb
<%= render "mystro_volley/versions/list", versions: @myversions %>

app/views/mystro_volley/versions/new.html.erb
<h1>New version</h1>

<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/mystro_volley/versions/show.html.erb
<% content_for :subnav_pills do %>
    <%= render "mystro_volley/common/breadcrumbs", project: @version.project, branch: @version.branch, version: @version %>
<% end %>

<h5>Files</h5>
<table class="table table-condensed table-striped tablesorter {sortlist: [[0,0]]}">
  <thead>
  <tr>
    <th>Name</th>
  </tr>
  </thead>
  <tbody>
  <% @version.files.each do |f| %>
  <tr><td><%= f %></td></tr>
  <% end %>
  </tbody>
</table>